name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: |
          sudo apt update && sudo apt install -y libxml2-utils
          curl -s -L -O https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz
          tar xzf hub*
          cp hub*/bin/hub hub
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Bump version
        run: |
          version=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
          parts=( ${version//./ } )
          bv=$((parts[1] + 1))
          new_version="${parts[0]}.${bv}.0"
          mvn versions:set -DnewVersion="${new_version}"
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
          git config user.name "simplexi-machine"
          git config user.email "platform+dev@simplexi.io"
          git add pom.xml
          git commit -m "[ci skip] bump version to $version"
          git push
          hub release create -m "jmxtrans-agent-$version-simplexi" -a target/jmxtrans-agent-$version.jar $(date +%Y%m%d%H%M%S)